"""Cheque template region definitions (docs/15_Cheque_Data_Extraction.md
S23: "cheque templates" such as `DEMO_BANK_TEMPLATE_V1`).

Per docs/18_Signature_Analysis.md S5: "For the MVP, template-based
signature-region extraction can be used if all sample cheques follow a
controlled layout" -- the Milestone 1 synthetic dataset does follow one
controlled, fixed layout (it was generated by our own renderer in
scripts/generate_synthetic_data.py), so a fixed-template approach is
appropriate here rather than a general-purpose cheque-layout detector.

Regions are stored as *fractions* of the image's width/height (not
absolute pixels) so they remain valid after Milestone 2's preprocessing
resizes the image -- extraction uses spatial/bounding-box information
(word centers falling inside a region) rather than only global text
parsing, per this milestone's requirements.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.services.ocr.engine import WordBox

TEMPLATE_NAME = "DEMO_BANK_TEMPLATE_V1"


@dataclass(frozen=True)
class FieldRegion:
    name: str
    x0: float
    y0: float
    x1: float
    y1: float


# Calibrated directly against scripts/generate_synthetic_data.py's
# render_cheque_image() layout on a 1200x560 canvas, expressed as
# fractions of (width, height) so they scale with any resize.
REGIONS: dict[str, FieldRegion] = {
    "bank_name": FieldRegion("bank_name", 0.015, 0.020, 0.260, 0.100),
    "date": FieldRegion("date", 0.730, 0.030, 0.980, 0.120),
    "cheque_number": FieldRegion("cheque_number", 0.730, 0.095, 0.980, 0.175),
    "payee_name": FieldRegion("payee_name", 0.015, 0.210, 0.360, 0.330),
    "amount": FieldRegion("amount", 0.015, 0.390, 0.230, 0.515),
    "amount_in_words": FieldRegion("amount_in_words", 0.015, 0.520, 0.780, 0.630),
    "account_number": FieldRegion("account_number", 0.015, 0.695, 0.280, 0.760),
    "routing_transit_number": FieldRegion("routing_transit_number", 0.015, 0.735, 0.310, 0.805),
    "signature": FieldRegion("signature", 0.620, 0.700, 0.960, 0.870),
    "micr_line": FieldRegion("micr_line", 0.015, 0.885, 0.560, 0.960),
}


def words_in_region(words: list[WordBox], region: FieldRegion, image_width: int, image_height: int) -> list[WordBox]:
    """Returns the words whose center point falls inside the region, in
    the OCR engine's own reading order (block/paragraph/line/word index)
    rather than a re-derived pixel-row order -- two words on the same
    printed line can differ by several pixels in measured top/height
    depending on ascenders/descenders, which made naive Y-bucketing
    unreliable."""
    x0 = region.x0 * image_width
    y0 = region.y0 * image_height
    x1 = region.x1 * image_width
    y1 = region.y1 * image_height

    matched = [w for w in words if x0 <= w.center[0] <= x1 and y0 <= w.center[1] <= y1]
    matched.sort(key=lambda w: (w.block_num, w.par_num, w.line_num, w.word_num))
    return matched


def region_text_and_confidence(words: list[WordBox]) -> tuple[str, float | None]:
    if not words:
        return "", None
    text = " ".join(w.text for w in words)
    confidences = [w.confidence for w in words if w.confidence >= 0]
    avg_conf = sum(confidences) / len(confidences) if confidences else None
    return text, avg_conf
