"""Mock/synthetic banking data repository (docs/16_Validation_Engine.md
S5, S35; ADR-0005).

Loads the Milestone 1 synthetic CSVs (data/mock_banking_data/) into
in-memory indices. This is the "Banking Data Repository" component
described in docs/09_Component_Architecture.md S14 -- the Validation
Engine talks only to this interface, never to the CSV files directly, so
Milestone 8 can substitute a PostgreSQL-backed implementation without
changing any validator code (NFR-006).

Per ADR-0005, this repository only ever reads synthetic/mock records
generated by scripts/generate_synthetic_data.py -- no real banking data.
"""

from __future__ import annotations

import csv
import threading
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Protocol

from app.core.config import settings


class BankingDataUnavailableError(Exception):
    """Raised when the mock banking data cannot be loaded at all (e.g.
    missing/corrupted CSV files) -- distinct from a normal "record not
    found" result. Callers must route the affected checks to NOT_CHECKED,
    never treat this as a silent PASS (docs/16 S42 Reliability: "A
    database or validation failure should not result in an incorrect
    automatic approval")."""


@dataclass(frozen=True)
class AccountRecord:
    account_number: str
    customer_id: str
    account_status: str
    account_type: str
    balance: float
    routing_number: str
    bank_code: str
    cheque_series_start: str
    cheque_series_end: str


@dataclass(frozen=True)
class ChequeIssuanceRecord:
    cheque_number: str
    account_number: str
    status: str
    payee_name: str
    amount_limit: float


@dataclass(frozen=True)
class DuplicateMatch:
    cheque_id: str
    account_number: str
    cheque_number: str
    payee_name: str
    amount: float
    cheque_date: str


@dataclass(frozen=True)
class TransactionRecord:
    transaction_id: str
    account_number: str
    transaction_date: str
    transaction_type: str
    amount: float
    payee_name: str


@dataclass(frozen=True)
class ImageHashRecord:
    """A previously processed cheque's image fingerprints (docs/19_Duplicate_Detection.md
    S8-S16 Level 2/3 duplicate evidence). Sourced from the subset of
    processed_cheques_history.csv rows that have hash values recorded --
    not every historical row has an associated image."""

    cheque_id: str
    account_number: str
    cheque_number: str
    image_hash: str
    perceptual_hash: str


class BankingDataRepository(Protocol):
    def get_account(self, account_number: str) -> AccountRecord | None: ...

    def get_cheque_issuance(self, account_number: str, cheque_number: str) -> ChequeIssuanceRecord | None: ...

    def find_duplicate(
        self, account_number: str, cheque_number: str, amount: float, cheque_date: str,
    ) -> DuplicateMatch | None: ...

    def get_account_transactions(self, account_number: str) -> list[TransactionRecord]: ...

    def get_image_hash_index(self) -> list[ImageHashRecord]: ...

    def find_by_account_and_cheque_number(
        self, account_number: str, cheque_number: str,
    ) -> list[DuplicateMatch]: ...

    def get_account_cheque_number_history(self, account_number: str) -> list[str]: ...


class CSVBankingDataRepository:
    """Loads data/mock_banking_data/{accounts,cheque_issuance,
    processed_cheques_history}.csv once and serves lookups from memory."""

    def __init__(self, data_dir: Path | None = None) -> None:
        self._data_dir = data_dir or settings.mock_banking_data_path
        self._lock = threading.Lock()
        self._accounts: dict[str, AccountRecord] | None = None
        self._issuance: dict[tuple[str, str], ChequeIssuanceRecord] | None = None
        self._processed_history: list[DuplicateMatch] | None = None
        self._image_hashes: list[ImageHashRecord] | None = None
        self._transactions: dict[str, list[TransactionRecord]] | None = None

    def _ensure_loaded(self) -> None:
        if self._accounts is not None:
            return
        with self._lock:
            if self._accounts is not None:
                return
            self._accounts = self._load_accounts()
            self._issuance = self._load_issuance()
            self._processed_history, self._image_hashes = self._load_processed_history()
            self._transactions = self._load_transactions()

    def _load_accounts(self) -> dict[str, AccountRecord]:
        path = self._data_dir / "accounts.csv"
        try:
            rows = self._read_csv(path)
        except OSError as exc:
            raise BankingDataUnavailableError(f"Unable to read {path}: {exc}") from exc

        accounts: dict[str, AccountRecord] = {}
        for row in rows:
            accounts[row["account_number"]] = AccountRecord(
                account_number=row["account_number"],
                customer_id=row["customer_id"],
                account_status=row["account_status"],
                account_type=row["account_type"],
                balance=float(row["balance"]),
                routing_number=row["routing_number"],
                bank_code=row["bank_code"],
                cheque_series_start=row["cheque_series_start"],
                cheque_series_end=row["cheque_series_end"],
            )
        return accounts

    def _load_issuance(self) -> dict[tuple[str, str], ChequeIssuanceRecord]:
        path = self._data_dir / "cheque_issuance.csv"
        try:
            rows = self._read_csv(path)
        except OSError as exc:
            raise BankingDataUnavailableError(f"Unable to read {path}: {exc}") from exc

        issuance: dict[tuple[str, str], ChequeIssuanceRecord] = {}
        for row in rows:
            key = (row["account_number"], row["cheque_number"])
            issuance[key] = ChequeIssuanceRecord(
                cheque_number=row["cheque_number"],
                account_number=row["account_number"],
                status=row["status"],
                payee_name=row["payee_name"],
                amount_limit=float(row["amount_limit"]),
            )
        return issuance

    def _load_processed_history(self) -> tuple[list[DuplicateMatch], list[ImageHashRecord]]:
        path = self._data_dir / "processed_cheques_history.csv"
        try:
            rows = self._read_csv(path)
        except OSError as exc:
            raise BankingDataUnavailableError(f"Unable to read {path}: {exc}") from exc

        history: list[DuplicateMatch] = []
        image_hashes: list[ImageHashRecord] = []
        for row in rows:
            if not row.get("cheque_number"):
                continue  # historical transactions with no associated cheque number
            history.append(DuplicateMatch(
                cheque_id=row["cheque_id"],
                account_number=row["account_number"],
                cheque_number=row["cheque_number"],
                payee_name=row["payee_name"],
                amount=float(row["amount"]),
                cheque_date=row["cheque_date"],
            ))
            if row.get("image_hash"):
                image_hashes.append(ImageHashRecord(
                    cheque_id=row["cheque_id"],
                    account_number=row["account_number"],
                    cheque_number=row["cheque_number"],
                    image_hash=row["image_hash"],
                    perceptual_hash=row.get("perceptual_hash") or "",
                ))
        return history, image_hashes

    def _load_transactions(self) -> dict[str, list[TransactionRecord]]:
        path = self._data_dir / "transactions.csv"
        try:
            rows = self._read_csv(path)
        except OSError as exc:
            raise BankingDataUnavailableError(f"Unable to read {path}: {exc}") from exc

        by_account: dict[str, list[TransactionRecord]] = {}
        for row in rows:
            record = TransactionRecord(
                transaction_id=row["transaction_id"],
                account_number=row["account_number"],
                transaction_date=row["transaction_date"],
                transaction_type=row["transaction_type"],
                amount=float(row["amount"]),
                payee_name=row["payee_name"],
            )
            by_account.setdefault(record.account_number, []).append(record)
        for txns in by_account.values():
            txns.sort(key=lambda t: t.transaction_date)
        return by_account

    @staticmethod
    def _read_csv(path: Path) -> list[dict]:
        if not path.exists():
            raise OSError(f"{path} does not exist")
        with path.open("r", newline="", encoding="utf-8") as handle:
            return list(csv.DictReader(handle))

    def get_account(self, account_number: str) -> AccountRecord | None:
        self._ensure_loaded()
        return self._accounts.get(account_number)

    def get_cheque_issuance(self, account_number: str, cheque_number: str) -> ChequeIssuanceRecord | None:
        self._ensure_loaded()
        return self._issuance.get((account_number, cheque_number))

    def find_duplicate(
        self, account_number: str, cheque_number: str, amount: float, cheque_date: str,
    ) -> DuplicateMatch | None:
        self._ensure_loaded()
        for record in self._processed_history:
            if (
                record.account_number == account_number
                and record.cheque_number == cheque_number
                and abs(record.amount - amount) < 0.01
                and record.cheque_date == cheque_date
            ):
                return record
        return None

    def get_account_transactions(self, account_number: str) -> list[TransactionRecord]:
        self._ensure_loaded()
        return list(self._transactions.get(account_number, []))

    def get_image_hash_index(self) -> list[ImageHashRecord]:
        self._ensure_loaded()
        return list(self._image_hashes)

    def find_by_account_and_cheque_number(
        self, account_number: str, cheque_number: str,
    ) -> list[DuplicateMatch]:
        self._ensure_loaded()
        return [
            r for r in self._processed_history
            if r.account_number == account_number and r.cheque_number == cheque_number
        ]

    def get_account_cheque_number_history(self, account_number: str) -> list[str]:
        self._ensure_loaded()
        return [r.cheque_number for r in self._processed_history if r.account_number == account_number]


_repository: CSVBankingDataRepository | None = None


def get_banking_repository() -> CSVBankingDataRepository:
    global _repository
    if _repository is None:
        _repository = CSVBankingDataRepository()
    return _repository


def reset_banking_repository_for_testing(data_dir: Path | None = None) -> CSVBankingDataRepository:
    """Test-only helper to point the singleton at a fresh/alternate data
    directory (e.g. a temp dir simulating unavailable banking data)."""
    global _repository
    _repository = CSVBankingDataRepository(data_dir)
    return _repository
